"""CLUTRR config modules."""

from clutrr.config.defaults import DEFAULT_CLUTRR_DATASET, DEFAULT_CLUTRR_ROOT
from clutrr.config.relation_schema import (
    ALL_POSSIBLE_TRANSITIVES_20,
    ID_RELATION_MAP_20,
    ID_RELATION_MAP_21_WITH_NOTHING,
    RELATION_ID_MAP_20,
    RELATION_ID_MAP_21_WITH_NOTHING,
    RELATION_NAMES_20,
)

__all__ = [
    "ALL_POSSIBLE_TRANSITIVES_20",
    "DEFAULT_CLUTRR_DATASET",
    "DEFAULT_CLUTRR_ROOT",
    "ID_RELATION_MAP_20",
    "ID_RELATION_MAP_21_WITH_NOTHING",
    "RELATION_ID_MAP_20",
    "RELATION_ID_MAP_21_WITH_NOTHING",
    "RELATION_NAMES_20",
]
