# CLUTRR baseline (no TSRA) with local Qwen3-8B without LoRA

model_type: qwen2.5-7b
model_name_or_path: /tos/lxh/models/qwen3_8

epochs: 5
lr: 0.00002
batch_size: 2
eval_batch_size: 4
num_workers: 0

root: data
dataset: data_089907f8

gpus: "1"
seed: 42

use_qlora: false
load_in_4bit: false
pooling: last_token
